model_name: ddpm
figure_path: ./results/Samples/ ddpm
model: ddpm
epochs: 5
batch_size: 128
generalize: 1
valrange: None
rp_length: 500
loss: mse
lim_data: 0
class_free:
  bool: 0
  guidance: 0
mod_ch: 24
ch_mul: [1, 2, 4]
num_res: 3
lr: 0.001
cosine_annealing: 1
dropout: 0.1
num_timesteps: 800
val_every_n_data: 4096
inf_mode: epoch
inf_every_n_step: 2000
inf_every_n_epoch: 1
conditionned: 
  bool: 0
  type: scalars
  scal_emb: 1 # 0 ou 1
  num_res: 2
  noise: 0.1
scheduler:
  name: cosine
  s: 0.1
  clipping_value: 0.98
